### PR TITLE
Make sure all chars are replaced, fix issue #396

### PR DESCRIPTION
**Pull request by lts-po**
make sure all chars are replaced, fix issue #396

This should fix problems with artifact names containing invalid characters:
"Error: Artifact name is not valid: xyz-rrr:0.1.2-dev.spdx.json. Contains the following character: Colon :"

[#396](https://github.com/anchore/sbom-action/issues/396)

### CODE REVIEW

**Comment by lts-po** [comment]
@kzantow hey, made a new pull request. amend didn't take it previous

**Comment by kzantow** [comment]
@lts-po do you mind if I push a quick update to fix the unrelated npm audit issue?

**Comment by kzantow** [comment]
(I went ahead and pushed the change, happy to back it out if you don't approve)

**Review by kzantow — APPROVED** [review]

**Comment by kzantow** [comment]
Thanks for the fix @lts-po!

**Pull request merged**
